services:
  mumble4j:
    image: ghcr.io/janhenke/mumble4j:latest
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8080}:8080/tcp
      - ${MANAGEMENT_PORT:-9000}:9000/tcp
      - ${MUMBLE_PORT:-64738}:64738
    environment:
      - quarkus.datasource.db.kind=${DB_KIND:-postgresql}
      - quarkus.datasource.jdbc.url=${DB_JDBC_URL}
      - quarkus.datasource.username=${DB_USERNAME}
      - quarkus.datasource.password=${DB_PASSWORD}
      - quarkus.oidc.auth.server.url=${OIDC_AUTH_SERVER_URL}
      - quarkus.oidc.client.id=${OIDC_CLIENT_ID}
      - quarkus.oidc.credentials.secret=${OIDC_CLIENT_SECRET}
      - quarkus.otel.exporter.otlp.endpoint=${OTEL_ENDPOINT:-http://localhost:4317}
