mumble:
  server:
    port: 64738

quarkus:
  datasource:
    jdbc:
      telemetry: true
    metrics:
      enabled: true
  jib:
    ports: ${quarkus.http.port:8080}, 64738
  log:
    category:
      "de.taujhe.mumble4j":
        level: INFO
  management:
    enabled: true
  oidc:
    health:
      enabled: true
  otel:
    metrics:
      enabled: true

"%dev":
  quarkus:
    console:
      color: true
    log:
      category:
        "de.taujhe.mumble4j":
          level: DEBUG
          min-level: TRACE
    management:
      enabled: false
