mumble:
  server:
    port: 64738

quarkus:
  http:
    access-log:
      enabled: true
  jib:
    ports: ${quarkus.http.port:8080}, 64738
  log:
    category:
      "de.taujhe.mumble4j":
        level: INFO
  otel:
    metrics:
      enabled: true

"%dev":
  quarkus:
    console:
      color: true
    log:
      category:
        "de.taujhe.mumble4j":
          level: DEBUG
          min-level: TRACE
